# Generated by Django 2.2.6 on 2019-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='productoventa',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
