# Generated by Django 2.2.6 on 2019-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20191112_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoventa',
            name='producto',
        ),
        migrations.AddField(
            model_name='productoventa',
            name='producto',
            field=models.ManyToManyField(blank=True, to='ventas.Producto'),
        ),
    ]
