# Generated by Django 2.2.6 on 2019-11-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20191112_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoventa',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
