# Generated by Django 2.2.6 on 2019-11-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20191115_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoventa',
            name='cantidad',
        ),
    ]
